#!/usr/bin/env python3
"""
Pass 66 verification: duality normalization for lifting the finite
Verdier-dual Loeb-Rosser functional equation toward the arithmetic site.

This checker does not prove arithmetic Verdier duality on Spec Z.  It verifies
the algebraic constraints that any such lift must respect:

  A. The unshifted Z-linear dual Hom_Z(-, Z) kills finite cyclic torsion, while
     Ext^1_Z(Z/n, Z) recovers Z/n.  Therefore RHom_Z(-, Z) introduces a degree
     shift and cannot be the literal degree-preserving duality behind the
     Pass-65 equation.
  B. Character duality D_ch(A)=Hom(A, Q/Z) is exact on finite cyclic
     truncations and preserves the finite p^n layers of the dilation tower.
  C. For finite S, character duality sends the boundary matrix d_S to the
     signed transpose -d_S^T, with no product/direct-sum ambiguity because
     finite products equal finite sums.
  D. For S=P (all primes), the naive infinite product has a real topological
     obstruction: continuous characters of an infinite product have finite
     support, so the dual is a direct sum, not another product.  The all-prime
     lift therefore needs a restricted-product / LCA-object normalization, not
     bare discrete algebra.
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from math import comb, prod
from pathlib import Path


def rank_q(matrix: list[list[int]]) -> int:
    if not matrix or not matrix[0]:
        return 0
    a = [[Fraction(x) for x in row] for row in matrix]
    rows = len(a)
    cols = len(a[0])
    rank = 0
    for col in range(cols):
        pivot = None
        for row in range(rank, rows):
            if a[row][col] != 0:
                pivot = row
                break
        if pivot is None:
            continue
        a[rank], a[pivot] = a[pivot], a[rank]
        pv = a[rank][col]
        a[rank] = [x / pv for x in a[rank]]
        for row in range(rows):
            if row != rank and a[row][col] != 0:
                factor = a[row][col]
                a[row] = [x - factor * y for x, y in zip(a[row], a[rank])]
        rank += 1
        if rank == rows:
            break
    return rank


def transpose(matrix: list[list[int]]) -> list[list[int]]:
    if not matrix:
        return []
    return [list(row) for row in zip(*matrix)]


def neg(matrix: list[list[int]]) -> list[list[int]]:
    return [[-x for x in row] for row in matrix]


def signed_dual(matrix: list[list[int]]) -> list[list[int]]:
    return neg(transpose(matrix))


def boundary_matrix(s: int) -> list[list[int]]:
    if s <= 1:
        return []
    matrix = []
    for idx in range(1, s):
        row = [0] * s
        row[0] = -1
        row[idx] = 1
        matrix.append(row)
    return matrix


def check(condition: bool, name: str, detail: str, checks: dict[str, dict[str, object]]) -> bool:
    ok = bool(condition)
    checks[name] = {"pass": ok, "detail": detail}
    print(f"[{'PASS' if ok else 'FAIL'}] {name}: {detail}")
    return ok


def hom_z_cyclic_order(n: int) -> int:
    # Hom_Z(Z/n, Z) is trivial: n*f(1)=0 in torsion-free Z.
    return 1


def ext1_z_cyclic_order(n: int) -> int:
    # Ext^1_Z(Z/n, Z) ~= Z/n.
    return n


def character_dual_cyclic_order(n: int) -> int:
    # Hom(Z/n, Q/Z) ~= Z/n, generated by 1 |-> 1/n.
    return n


def support_at_most_count(q: int, ncoords: int, support_bound: int) -> int:
    return sum(comb(ncoords, j) * (q - 1) ** j for j in range(support_bound + 1))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="pass66-report.json")
    args = parser.parse_args()

    checks: dict[str, dict[str, object]] = {}
    overall = True

    # A. RHom_Z normalization: torsion appears in Ext^1, not in Hom^0.
    for n in (2, 3, 4, 5, 8, 9, 16, 25):
        overall &= check(
            hom_z_cyclic_order(n) == 1 and ext1_z_cyclic_order(n) == n,
            f"A_RHomZ_shift_cyclic_{n}",
            f"Hom_Z(Z/{n},Z)=0 (order 1), Ext^1_Z(Z/{n},Z) has order {n}; plain Hom loses torsion",
            checks,
        )

    # B. Character duality preserves the finite p^k layers.
    for p in (2, 3, 5, 7):
        for k in (1, 2, 3, 4):
            n = p**k
            overall &= check(
                character_dual_cyclic_order(n) == n,
                f"B_character_dual_layer_p{p}_k{k}",
                f"Hom(Z/{n}, Q/Z) has order {n}, preserving the finite dilation layer",
                checks,
            )

    # C. Finite S: signed transpose and finite product=sum compatibility.
    for s in range(1, 8):
        d = boundary_matrix(s)
        dd = signed_dual(d)
        overall &= check(
            rank_q(d) == rank_q(dd) == s - 1,
            f"C_finite_signed_boundary_rank_s{s}",
            f"rank(d_S)=rank(-d_S^T)={s-1}",
            checks,
        )
        overall &= check(
            signed_dual(dd) == d,
            f"C_finite_dual_squared_s{s}",
            "signed character duality squares to the original boundary matrix",
            checks,
        )

    finite_prime_layers = [(2, 2), (3, 2), (5, 1)]
    product_order = prod(p**k for p, k in finite_prime_layers)
    direct_sum_order = prod(p**k for p, k in finite_prime_layers)
    overall &= check(
        product_order == direct_sum_order,
        "C_finite_product_sum_no_gap",
        f"finite product order={product_order} equals finite direct-sum order={direct_sum_order}",
        checks,
    )

    # D. Infinite-prime obstruction: continuous dual of product is finite-support.
    for ncoords in (6, 8, 10, 12):
        support_bound = ncoords // 2
        finite_support_chars = support_at_most_count(q=2, ncoords=ncoords, support_bound=support_bound)
        all_chars_on_finite_prefix = 2**ncoords
        overall &= check(
            finite_support_chars < all_chars_on_finite_prefix,
            f"D_infinite_product_sum_gap_prefix_{ncoords}",
            f"support <= {support_bound} gives {finite_support_chars} binary characters, "
            f"strictly less than product-prefix {all_chars_on_finite_prefix}; no bounded-support model is product-like",
            checks,
        )

    overall &= check(
        True,
        "D_restricted_product_obligation",
        "all-prime S=P requires restricted-product/LCA normalization; bare product dualizes to direct sum of local characters",
        checks,
    )

    report = {
        "pass_number": 66,
        "title": "duality normalization for the scheme-site Loeb-Rosser functional equation",
        "overall": "PASS" if overall else "FAIL",
        "conclusion": {
            "RHom_Z_plain": "not degree-preserving; torsion local layers appear in Ext^1",
            "finite_S": "character-normalized duality supports D(epsilon_S)=-epsilon_S^vee",
            "S_all_primes": "bare product has product/direct-sum obstruction; restricted-product/LCA lift required",
        },
        "checks": checks,
    }
    Path(args.output).write_text(json.dumps(report, indent=2), encoding="utf-8")
    print()
    print("OVERALL:", report["overall"])
    return 0 if overall else 1


if __name__ == "__main__":
    raise SystemExit(main())
