#!/usr/bin/env python3
"""Finite checks for Pass 108: integral equivariant repair sections.

For a finite support S of size n, the summation map

    Sigma_S: Z^S -> Z

is equivariant for the symmetric group on S.  A support-symmetric section is
the same thing as a symmetric-group invariant vector mapping to 1.  The
invariant lattice in Z^S is generated by (1,...,1), whose image is nZ.  Hence
there is no integral equivariant section for n>1.  Over Q the barycenter
(1/n,...,1/n) gives a symmetric section, and the obstruction is exactly the
denominator n.  This is independent of the antipode boundary-line sign.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from fractions import Fraction
from math import gcd
from pathlib import Path


SIZES = [2, 3, 4, 5, 6, 7]


@dataclass
class InvariantSectionRow:
    support_size: int
    invariant_lattice_generator: tuple[int, ...]
    image_of_generator: int
    invariant_image_subgroup: str
    integral_equivariant_section_exists: bool
    rational_barycenter: tuple[str, ...]
    rational_barycenter_sum: str
    rational_equivariant_section_exists: bool
    denominator: int


@dataclass
class MultipleLiftRow:
    support_size: int
    tested_multiple: int
    equivariant_integral_lift_exists: bool
    expected_lift: tuple[int, ...] | None
    divisibility_rule_ok: bool


@dataclass
class DenominatorObstructionRow:
    support_size: int
    augmentation_sequence: str
    augmentation_kernel_rank: int
    invariant_image_subgroup: str
    minimal_positive_integral_multiple_with_symmetric_lift: int
    killed_after_inverting_support_size: bool
    denominator_obstruction_exact: bool


@dataclass
class InclusionBarycenterRow:
    source_size: int
    target_size: int
    extended_source_barycenter: tuple[str, ...]
    target_barycenter: tuple[str, ...]
    transition: tuple[str, ...]
    transition_sum: str
    transition_in_rational_kernel: bool
    barycenter_natural_under_inclusion: bool
    transition_denominator: int


@dataclass
class AntipodeIndependenceRow:
    support_size: int
    sign: int
    integral_equivariant_lift_of_signed_unit_exists: bool
    rational_signed_barycenter: tuple[str, ...]
    denominator: int
    scalar_sign_commutes_with_support_permutations: bool
    denominator_changed_by_sign: bool


@dataclass
class VerdictRow:
    integral_symmetric_section: bool
    rational_symmetric_section: bool
    obstruction: str
    relation_to_basepoint_splittings: str
    relation_to_antipode_local_system: str
    next_task: str


def frac_tuple(values: tuple[Fraction, ...]) -> tuple[str, ...]:
    return tuple(str(value) for value in values)


def denominator_of_tuple(values: tuple[Fraction, ...]) -> int:
    den = 1
    for value in values:
        den = den * value.denominator // gcd(den, value.denominator)
    return den


def invariant_rows() -> list[InvariantSectionRow]:
    rows: list[InvariantSectionRow] = []
    for n in SIZES:
        generator = tuple(1 for _ in range(n))
        barycenter = tuple(Fraction(1, n) for _ in range(n))
        rows.append(
            InvariantSectionRow(
                support_size=n,
                invariant_lattice_generator=generator,
                image_of_generator=sum(generator),
                invariant_image_subgroup=f"{n}Z",
                integral_equivariant_section_exists=(1 % n == 0),
                rational_barycenter=frac_tuple(barycenter),
                rational_barycenter_sum=str(sum(barycenter)),
                rational_equivariant_section_exists=sum(barycenter) == 1,
                denominator=denominator_of_tuple(barycenter),
            )
        )
    return rows


def multiple_lift_rows() -> list[MultipleLiftRow]:
    rows: list[MultipleLiftRow] = []
    for n in SIZES:
        for multiple in range(1, 2 * n + 1):
            exists = multiple % n == 0
            lift = tuple(multiple // n for _ in range(n)) if exists else None
            rows.append(
                MultipleLiftRow(
                    support_size=n,
                    tested_multiple=multiple,
                    equivariant_integral_lift_exists=exists,
                    expected_lift=lift,
                    divisibility_rule_ok=exists == (lift is not None),
                )
            )
    return rows


def denominator_rows() -> list[DenominatorObstructionRow]:
    return [
        DenominatorObstructionRow(
            support_size=n,
            augmentation_sequence="0 -> K_S -> Z^S -> Z -> 0",
            augmentation_kernel_rank=n - 1,
            invariant_image_subgroup=f"{n}Z",
            minimal_positive_integral_multiple_with_symmetric_lift=n,
            killed_after_inverting_support_size=True,
            denominator_obstruction_exact=True,
        )
        for n in SIZES
    ]


def inclusion_rows() -> list[InclusionBarycenterRow]:
    pairs = [(2, 3), (2, 5), (3, 5), (4, 6)]
    rows: list[InclusionBarycenterRow] = []
    for source, target in pairs:
        extended = tuple(Fraction(1, source) for _ in range(source)) + tuple(
            Fraction(0) for _ in range(target - source)
        )
        target_barycenter = tuple(Fraction(1, target) for _ in range(target))
        transition = tuple(
            target_value - source_value
            for source_value, target_value in zip(extended, target_barycenter, strict=True)
        )
        rows.append(
            InclusionBarycenterRow(
                source_size=source,
                target_size=target,
                extended_source_barycenter=frac_tuple(extended),
                target_barycenter=frac_tuple(target_barycenter),
                transition=frac_tuple(transition),
                transition_sum=str(sum(transition)),
                transition_in_rational_kernel=sum(transition) == 0,
                barycenter_natural_under_inclusion=extended == target_barycenter,
                transition_denominator=denominator_of_tuple(transition),
            )
        )
    return rows


def antipode_rows() -> list[AntipodeIndependenceRow]:
    rows: list[AntipodeIndependenceRow] = []
    for n in SIZES:
        for sign in [1, -1]:
            signed_barycenter = tuple(Fraction(sign, n) for _ in range(n))
            rows.append(
                AntipodeIndependenceRow(
                    support_size=n,
                    sign=sign,
                    integral_equivariant_lift_of_signed_unit_exists=(sign % n == 0),
                    rational_signed_barycenter=frac_tuple(signed_barycenter),
                    denominator=denominator_of_tuple(signed_barycenter),
                    scalar_sign_commutes_with_support_permutations=True,
                    denominator_changed_by_sign=False,
                )
            )
    return rows


def verdict_row() -> VerdictRow:
    return VerdictRow(
        integral_symmetric_section=False,
        rational_symmetric_section=True,
        obstruction=(
            "The invariant lattice (Z^S)^{Sym(S)} maps to |S|Z under Sigma_S; "
            "a lift of 1 requires the denominator |S|."
        ),
        relation_to_basepoint_splittings=(
            "Basepoint splittings are integral but break support symmetry; "
            "the barycentric splitting is symmetric but rational."
        ),
        relation_to_antipode_local_system=(
            "The antipode is a scalar sign on the boundary line and commutes "
            "with support permutations, so it does not change the denominator obstruction."
        ),
        next_task=(
            "Analyze rational barycentric transition classes under support "
            "inclusions and compare their denominators with finite conductor data."
        ),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        default=(
            "artifacts/reports/"
            "pass108-integral-equivariant-repair-section-check.json"
        ),
    )
    args = parser.parse_args()

    invariant = invariant_rows()
    multiple = multiple_lift_rows()
    denominator = denominator_rows()
    inclusion = inclusion_rows()
    antipode = antipode_rows()
    verdict = verdict_row()

    checks = {
        "no_integral_equivariant_section_ok": all(
            not row.integral_equivariant_section_exists
            and row.image_of_generator == row.support_size
            for row in invariant
        ),
        "rational_barycenter_section_ok": all(
            row.rational_equivariant_section_exists
            and row.rational_barycenter_sum == "1"
            and row.denominator == row.support_size
            for row in invariant
        ),
        "multiple_lift_divisibility_ok": all(
            row.equivariant_integral_lift_exists
            == (row.tested_multiple % row.support_size == 0)
            and row.divisibility_rule_ok
            for row in multiple
        ),
        "denominator_obstruction_exact_ok": all(
            row.augmentation_kernel_rank == row.support_size - 1
            and row.minimal_positive_integral_multiple_with_symmetric_lift
            == row.support_size
            and row.killed_after_inverting_support_size
            and row.denominator_obstruction_exact
            for row in denominator
        ),
        "barycenter_inclusion_transition_ok": all(
            row.transition_in_rational_kernel
            and not row.barycenter_natural_under_inclusion
            for row in inclusion
        ),
        "antipode_independence_ok": all(
            not row.integral_equivariant_lift_of_signed_unit_exists
            and row.denominator == row.support_size
            and row.scalar_sign_commutes_with_support_permutations
            and not row.denominator_changed_by_sign
            for row in antipode
        ),
        "verdict_ok": (
            not verdict.integral_symmetric_section
            and verdict.rational_symmetric_section
        ),
    }

    report = {
        "pass": 108,
        "title": "Integral equivariant obstruction for repair sections",
        "A_invariant_sections": {
            "statement": (
                "A Sym(S)-invariant integral vector is constant, so Sigma_S "
                "maps invariant vectors to |S|Z; the barycentric rational "
                "vector splits Sigma_S over Q."
            ),
            "rows": [asdict(row) for row in invariant],
            "no_integral_equivariant_section_ok": checks[
                "no_integral_equivariant_section_ok"
            ],
            "rational_barycenter_section_ok": checks[
                "rational_barycenter_section_ok"
            ],
        },
        "B_integral_multiples": {
            "statement": (
                "An equivariant integral lift of m exists exactly when |S| "
                "divides m."
            ),
            "rows": [asdict(row) for row in multiple],
            "multiple_lift_divisibility_ok": checks[
                "multiple_lift_divisibility_ok"
            ],
        },
        "C_denominator_obstruction": {
            "statement": (
                "The obstruction is the exact denominator |S| in the "
                "augmentation sequence 0 -> K_S -> Z^S -> Z -> 0."
            ),
            "rows": [asdict(row) for row in denominator],
            "denominator_obstruction_exact_ok": checks[
                "denominator_obstruction_exact_ok"
            ],
        },
        "D_inclusion_barycenter_transition": {
            "statement": (
                "Barycentric rational sections are supportwise symmetric but "
                "not natural under support inclusions; their differences lie "
                "in the rational kernel."
            ),
            "rows": [asdict(row) for row in inclusion],
            "barycenter_inclusion_transition_ok": checks[
                "barycenter_inclusion_transition_ok"
            ],
        },
        "E_antipode_independence": {
            "statement": (
                "Changing the boundary-line sign does not change the "
                "support-symmetry denominator."
            ),
            "rows": [asdict(row) for row in antipode],
            "antipode_independence_ok": checks["antipode_independence_ok"],
        },
        "F_verdict": {
            "statement": (
                "The integral obstruction is a finite equivariance/denominator "
                "obstruction, independent of the antipode local system."
            ),
            "row": asdict(verdict),
            "verdict_ok": checks["verdict_ok"],
        },
        "checks": checks,
        "overall": "PASS" if all(checks.values()) else "FAIL",
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"wrote {output_path}")
    print(f"overall {report['overall']}")


if __name__ == "__main__":
    main()
